### ISSUE TITLE
Komplettera

### ISSUE THREAD

**Issue by 1dv449** [AndreasAnemyrLNU/1DV449_AA223IG#1]
Big Data
Web of things

**Comment by AndreasAnemyrLNU** [comment]
Big Data 

I dagen samhälle finns miljontals användare av internet. Med den teknik som idag finns i bla smartphones är det en "piece of cake" att samla in mängder av information. Man skulle kunna säga att alla användare lämnar "breadcrumbs" efter sig och att det pga av detta är möjligt att använda dessa spår för att helt enkelt "tracka" användare. Själv kan jag tycka att det intressanta är att man kan använda denna infromationen i olika former av algoritmer. Big Data med dagens möjligheter, kanske främst genom att så många ständigt är uppkopplade, ger dagens utvecklar otaliga möjligheter för att utveckla nya typer av applikationer och algoritmer. Något som för många för bara femton år sedan vore fullständigt omöjligt. Självklart skulle dessa applikationer både kunnna grunda sig på "realtidsdata" genererat från användare, men även historiska data över längre tid som sparats persistent.
Inte sällan påpekas "det otäcka" i att den personliga integriteten eventuellt skulle kunna påverkas negativt. Som utvecklar ser jag det som "vårt" ansvar att förvalta möjligheter som big data ger och utveckla och forma internet i gott syfte.

Källor:
https://www.youtube.com/watch?v=buJUojhs80E
http://www.svd.se/big-data-gor-om-var-varld-i-grunden_8076288

**Comment by AndreasAnemyrLNU** [comment]
Web of things

År 2009 höll Tim Berners-Less ett kort föredrag om länkat data. Han nämner att han ursprungligen utvecklade http för att få ett effektivare sätt att hantera dokument. Dokument var således den ursprungliga ändamålet för protokollet. Nu efter tjugo år har saker kanske på ett sätt inte direkt förändrats, däremot så är det som det ofta är. Nya idéer och insikter kommer med tiden. Tim nästintill håller ett brandtal om att vi ska dela data med varandra. Intressant är när han nämner Hans Rosling använt länkat data från flera olika källor via http för att generera ut data baserat från flera olika datakällor, men som får en naturlig koppling genom länkarna som http erbjuder.

Internet idag består inte endast vad som var tanken från början, dvs dokument. Produkter, människor och platser mm. är idag saker som återfinns på nätet. Vi har ett internet av saker som ger möjligheter att generera nya dokument och applikationer mm. Tim Berners-Lee nämner några viktiga saker i föredraget: Bl.a nämner han vikten av att dela med sig data. Gärna genom ett lämpligt format såsom json 


Källor:
http://www.ted.com/talks/tim_berners_lee_on_the_next_web#t-484161

**Comment by AndreasAnemyrLNU** [comment]
@1dv449 
Hej!
Komplettering för labb enligt Issues Komplettera #1  
finns nu i README.md  //Mvh Andréas

**Comment by 1dv449** [comment]
Det är ok. stänger denna issue
